// Code generated by "stringer -type=PropVersion -linecomment"; DO NOT EDIT.

package develop

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModVersion-1]
	_ = x[MinecraftVersion-2]
	_ = x[ArchitecturyVersion-3]
	_ = x[FabricLoaderVersion-4]
	_ = x[FabricApiVersion-5]
	_ = x[YarnMappingsVersion-6]
	_ = x[ForgeVersion-7]
	_ = x[ForgeMappingsVersion-8]
	_ = x[QuiltLoaderVersion-9]
	_ = x[QuiltFabricApiVersion-10]
	_ = x[QuiltMappingsVersion-11]
	_ = x[NeoForgeVersion-12]
}

const _PropVersion_name = "VersionMinecraftArchitecturyFabric LoaderFabric APIYarn MappingsForgeForge MappingsQuilt LoaderQuilted Fabric APIQuilt MappingsNeoForgeVersion"

var _PropVersion_index = [...]uint8{0, 7, 16, 28, 41, 51, 64, 69, 83, 95, 113, 127, 142}

func (i PropVersion) String() string {
	i -= 1
	if i < 0 || i >= PropVersion(len(_PropVersion_index)-1) {
		return "PropVersion(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PropVersion_name[_PropVersion_index[i]:_PropVersion_index[i+1]]
}
